export const tekstovi = {
  hero: {
    naslov: 'NextPixel Media',
    podnaslov: 'Foto · Video · Dron',
    opis: 'Sadržaj za firme, nekretnine i događaje — Gradiška, Banja Luka i okolina.',
  },
  statement: {
    prvi: 'Ljudi biraju gdje će jesti, gdje će trenirati i koga će zvati —',
    naglasak: 'po slikama.',
    drugi: 'Tvoje su slabije nego tvoj posao.',
  },
  intro: 'Nas je dvoje. Snimamo vikendom, jedan do dva posla mjesečno — i zato svaki odradimo do kraja.',
  citat: 'Rok koji ispuniš svaki put vrijedi više od roka koji zvuči brzo i probije se.',
  rokoviNaslov: 'Rokovi',
  rokoviNaljepnice: ['bez izgovora', 'zapisano u ponudi', 'isto svaki put'],
  cta: {
    naslov: 'Imaš objekat, event ili firmu za snimanje?',
    email: 'nikola@nextpixel.media',
  },
  footerKartica: { naslov: 'Treba ti i sajt?', link: 'nextpixel.dev' },
  uslugeHero: 'Jedna ekipa. Svaki kadar. Svaki format.',
  radoviHero: { naslov: 'Naš rad.', opis: 'Izbor onoga što smo snimili.' },
  oNama: 'NextPixel Media je media strana NextPixel-a. .dev gradi sajt — mi snimamo ono što na njemu stoji.',
  kontaktHero: 'Dobro došao. Da se upoznamo.',
  kontaktObecanje: 'Javljam se u roku od dva sata.',
  kontaktForma: {
    labela: 'Razgovor',
    metaOpis: 'Pošalji upit za snimanje. Javljamo se u roku od dva sata.',
    brojevi: ['01', '02', '03', '04', '05', '06'],
    sta: { legenda: 'Šta ti treba', naslov: 'Šta ti treba?' },
    polja: {
      ime: 'Ime i prezime ili firma',
      kontakt: 'Email ili telefon',
      kadaGdje: 'Kada i gdje',
    },
    gdje: { legenda: 'Gdje ćeš koristiti materijal', naslov: 'Gdje ćeš koristiti materijal?' },
    poruka: 'Poruka',
    placeholder: 'Upiši',
    saljem: 'Šaljem…',
    posalji: 'Pošalji',
    greska: 'Slanje nije uspjelo. Pošalji direktno na',
    primljeno: 'Primljeno.',
  },
  chrome: {
    nav: {
      cta: 'Započni projekat',
      meniOtvori: 'Meni',
      meniZatvori: 'Zatvori',
      logoAria: 'NextPixel Media, početna',
    },
    meni: {
      copyright: '© 2026 NextPixel Media — Gradiška, BA',
      oznaka: 'Foto · Video · Dron',
    },
    footer: {
      copyright: '© 2026 NextPixel Media. Sva prava zadržana.',
      uslovi: 'Uslovi',
      privatnost: 'Privatnost',
    },
    nijePronadjeno: {
      naslov: '404',
      opis: 'Ova stranica ne postoji.',
      dugme: 'Nazad na početnu',
    },
    greska: {
      naslov: 'Nešto je puklo',
      opis: 'Pokušaj ponovo. Ako se ponovi, javi se na nikola@nextpixel.media',
      dugme: 'Pokušaj ponovo',
    },
  },
} as const
